#!/usr/bin/env python3
"""Generate the hash-pinned requirements file the AppImage installs from.

``requirements.lock`` pins versions but carries no hashes, so the bundling step
took whatever PyPI served for those versions -- inside an artifact that is then
signed and published (issue #255). The Flatpak has been the good example all
along: its ``python3-*.yaml`` manifests vendor the sdists with ``sha256:``.

This writes ``packaging/appimage/requirements.hashed.txt``, which the recipe
installs with ``--require-hashes``. Only the files that could be selected for
the bundle are listed -- the AppImage is x86_64 and its interpreter comes from
Ubuntu noble -- so a base-image change that moves the interpreter fails loudly
with "no hash matched" instead of quietly installing something else.

Run it after ``make lock-deps``:

    python3 packaging/appimage/hash_lock.py

PyGObject and pycairo are skipped: the bundle takes them from the apt packages
the recipe pulls in, never from PyPI.
"""
import json
import re
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
LOCK = REPO_ROOT / "requirements.lock"
OUTPUT = REPO_ROOT / "packaging/appimage/requirements.hashed.txt"

#: Provided by the bundled apt packages (python3-gi, python3-cairo), so the
#: recipe must never pull them from PyPI.
FROM_APT = {"pygobject", "pycairo"}

#: The interpreter the bundle carries. Ubuntu noble ships CPython 3.12; the
#: AppImage is x86_64 only (packaging/build.sh refuses any other host).
INTERPRETER = "cp312"
PLATFORM = re.compile(r"(manylinux[0-9_.]*_x86_64|manylinux2014_x86_64)")


def _selectable(filename):
    """Could pip choose this file for the AppImage's interpreter?"""
    if filename.endswith(".tar.gz") or filename.endswith(".zip"):
        return True  # the sdist, for a --no-binary build
    if not filename.endswith(".whl"):
        return False
    if filename.endswith("-none-any.whl"):
        return True  # pure Python
    tags = filename[: -len(".whl")]
    if not PLATFORM.search(tags):
        return False
    return INTERPRETER in tags or "abi3" in tags


def main():
    lines = [
        "# Generated by packaging/appimage/hash_lock.py -- do not edit by hand.",
        "#",
        "# The AppImage installs from this file with --require-hashes, so what",
        "# lands inside a signed release artifact is fixed by content, not by",
        "# whatever PyPI serves for the pinned version (issue #255). Versions",
        "# come from requirements.lock; tests/test_reproducible_builds.py fails",
        "# when the two disagree.",
        "#",
        "# Regenerate after `make lock-deps`:",
        "#     python3 packaging/appimage/hash_lock.py",
        "",
    ]
    for entry in LOCK.read_text(encoding="utf-8").split():
        name, _, version = entry.partition("==")
        if not version or name.lower() in FROM_APT:
            continue
        url = f"https://pypi.org/pypi/{name}/{version}/json"
        with urllib.request.urlopen(url) as response:
            release = json.load(response)
        hashes = [
            f["digests"]["sha256"]
            for f in release["urls"]
            if _selectable(f["filename"])
        ]
        if not hashes:
            raise SystemExit(f"{name}=={version}: no file matches {INTERPRETER}/x86_64")
        rendered = " \\\n    ".join(f"--hash=sha256:{h}" for h in hashes)
        lines.append(f"{name}=={version} \\\n    {rendered}")
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
