"""The in-game control bar, drawn by RetroArch itself (issue #469).

The game's controls used to live in a libadwaita "game window" that captured
RetroArch's X11 window into a GTK one: X11-only, fragile across setups, and a
hop on every click -- the button sent a command down RetroArch's command
channel, and RetroArch acted on it at its next poll. They are drawn *inside*
RetroArch now, as an input overlay: a click on an overlay button is
RetroArch's own input, it works on any console, and the only volume indicator
left is RetroArch's own.

Two pieces, both shipped in ``openemux/data/overlay``:

- ``openemux-bar.cfg`` and its PNGs, generated by ``scripts/build_overlay.py``:
  the bar, as one overlay page per combination of its toggles (pause, mute,
  fast-forward, slow motion, turbo) and shown/hidden -- overlays have no state
  of their own, so a toggle is a page swap.
- ``margin.glsl`` / ``margin.slang``: an overlay is drawn *over* the game, and
  RetroArch has no setting that reserves room for one. This last shader pass
  shrinks the image so the bottom strip stays clear, and unlike a custom
  viewport it follows the window through resizes and fullscreen. A console's
  own shader keeps working: the pass is appended to the end of its preset, and
  hiding the bar swaps to the same preset without it (``prepare_shaders``).

RetroArch does not read them from the package: ``stage_assets`` copies them to
the runtime directory first. In the Flatpak the package lives under OpenEmux's
own ``/app``, which RetroArch's Flatpak cannot see (issue #482).
"""

import logging
import re
import shutil
from pathlib import Path

from openemux.core.platform import cfg_path
from openemux.core.video_driver import preset_backends

logger = logging.getLogger(__name__)

OVERLAY_DIR = Path(__file__).resolve().parent.parent / "data" / "overlay"
OVERLAY_CFG = OVERLAY_DIR / "openemux-bar.cfg"

#: The margin pass, per preset backend.
MARGIN_SHADER = {"glsl": OVERLAY_DIR / "margin.glsl", "slang": OVERLAY_DIR / "margin.slang"}

#: The window a game opens in. The bar is laid out on a 4:3 box and
#: auto-scaled to the window's height, so any landscape window keeps it on the
#: bottom edge; only one narrower than 4:3 would lift it. 16:9 is what most
#: screens are, so the window starts out as their shape.
WINDOW_SIZE = (1280, 720)

#: The share of the screen's height kept for the bar while it is shown. Must
#: agree with ``MARGIN`` in the margin shaders and STRIP / H in
#: scripts/build_overlay.py.
MARGIN = 60.0 / 720.0

#: Where ``stage_assets`` puts the copies, under the runtime directory.
STAGED_DIR_NAME = "overlay"

_KEY_VALUE = re.compile(r'^\s*([A-Za-z0-9_]+)\s*=\s*"?([^"]*)"?\s*$')
_PASS_PATH = re.compile(r"^shader\d+$")


def stage_assets(runtime_dir):
    """Copy the bar's files where RetroArch can read them; return the folder.

    The package's own copy is only reachable from OpenEmux's side: in the
    Flatpak it sits under OpenEmux's ``/app``, and the RetroArch Flatpak sees
    neither that nor ``/usr``, ``/opt`` or an AppImage's mount -- the bar
    simply never appeared (issue #482). The runtime directory already holds
    the ``--appendconfig`` file, so every RetroArch reads it. A file already
    there with the same bytes is left alone. Falls back to the package's
    folder, with a warning, when the copy cannot be made.
    """
    target = Path(runtime_dir) / STAGED_DIR_NAME
    try:
        target.mkdir(parents=True, exist_ok=True)
        for source in OVERLAY_DIR.iterdir():
            if not source.is_file():
                continue
            copy = target / source.name
            if copy.is_file() and copy.read_bytes() == source.read_bytes():
                continue
            shutil.copyfile(source, copy)
    except OSError as exc:
        logger.warning("in-game bar: cannot copy its files to %s: %s", target, exc)
        return OVERLAY_DIR
    return target


def runtime_overrides(overlay_dir=OVERLAY_DIR):
    """The ``--appendconfig`` lines that turn the bar on for one launch.

    ``overlay_dir`` is where the bar's files are, as ``stage_assets`` left them.
    """
    width, height = WINDOW_SIZE
    return {
        "input_overlay_enable": '"true"',
        "input_overlay": f'"{cfg_path(Path(overlay_dir) / OVERLAY_CFG.name)}"',
        # RetroArch's own default swaps the overlay for the system's
        # "preferred" one when content loads -- a touch gamepad, on a desktop
        # -- wherever it ships one: PlayStation and PSP do, so their games came
        # up with that gamepad over them and no bar at all (issue #471).
        "input_overlay_enable_autopreferred": '"false"',
        "input_overlay_opacity": '"1.000000"',
        # The dock is a 16:9 layout: keep its buttons square whatever the
        # window's shape, instead of stretching them with it.
        "input_overlay_auto_scale": '"true"',
        "input_overlay_show_mouse_cursor": '"true"',
        "video_mouse_cursor": '"true"',
        # A gamepad is how most people play; hiding the bar when one is
        # plugged in would hide it for almost everyone.
        "input_overlay_hide_when_gamepad_connected": '"false"',
        "input_overlay_hide_in_menu": '"false"',
        "input_overlay_behind_menu": '"false"',
        # True fullscreen recreates the window, and with the X input driver
        # the overlay stops seeing clicks afterwards -- including the one that
        # would leave fullscreen. Windowed fullscreen keeps it working.
        "video_windowed_fullscreen": '"true"',
        # The core's own aspect: the margin pass shrinks the viewport RetroArch
        # computes, so that viewport has to be the right shape to begin with.
        "aspect_ratio_index": '"22"',
        "video_window_custom_size_enable": '"true"',
        "window_position_width": f'"{width}"',
        "window_position_height": f'"{height}"',
        "video_window_save_positions": '"false"',
        # The bar's turbo button presses RetroArch's turbo bind once per click,
        # which only means "start/stop firing" in Single Button (Toggle) mode
        # (2 in 1.22: Classic, Classic Toggle, Single Button Toggle, Single
        # Button Hold). The other modes want turbo *held* with a button, and
        # an overlay click cannot hold anything.
        "input_turbo_enable": '"true"',
        "input_turbo_mode": '"2"',
    }


def _backend_for(video_driver):
    backends = preset_backends(video_driver)
    return backends[0] if backends else None


#: The two presets RetroArch's shader directory holds while the bar is on.
#: "Next shader" cycles through that directory in name order, starting from
#: its first entry, so the order is the whole mechanism: the launch loads
#: "shown", and the first hide (``overlay_next|shader_next``) lands on
#: "hidden". The names are also what RetroArch's "Shader: ..." notice prints.
HIDDEN_PRESET = "Controls hidden"
SHOWN_PRESET = "Controls shown"


def _absolute_passes(source):
    """The user's preset as lines with absolute paths, and its pass count.

    ``None`` when it cannot be extended safely: unreadable, a ``#reference``
    chain (the passes live in another file), or no pass count. Paths in a
    preset are relative to the preset; the copies live elsewhere, so the pass
    files and the lookup textures it names are rewritten.
    """
    try:
        text = source.read_text(encoding="utf-8", errors="replace")
    except OSError as exc:
        logger.warning("in-game bar: cannot read %s: %s", source, exc)
        return None
    values, lines = {}, []
    for raw in text.splitlines():
        if raw.strip().startswith("#reference"):
            logger.info("in-game bar: %s uses #reference; margin not appended", source)
            return None
        match = _KEY_VALUE.match(raw)
        if match:
            values[match.group(1)] = match.group(2)
        lines.append(raw)
    try:
        passes = int(values.get("shaders", ""))
    except ValueError:
        logger.info("in-game bar: %s has no pass count; margin not appended", source)
        return None

    path_keys = {key for key in values if _PASS_PATH.match(key)}
    path_keys.update(t for t in values.get("textures", "").split(";") if t)
    out = []
    for raw in lines:
        match = _KEY_VALUE.match(raw)
        if not match:
            out.append(raw)
            continue
        key, value = match.groups()
        if key == "shaders":
            continue
        if key in path_keys and value and not Path(value).is_absolute():
            value = cfg_path((source.parent / value).resolve())
        out.append(f'{key} = "{value}"')
    return out, passes


def prepare_shaders(user_preset, video_driver, runtime_dir, overlay_dir=OVERLAY_DIR):
    """The preset to load and the shader directory to point RetroArch at.

    Returns ``(preset, shader_dir)``. ``shader_dir`` holds exactly the two
    presets above: the console's own shader (or a plain pass when it has
    none) with and without the margin pass appended. ``(user_preset, None)``
    when that cannot be done -- a driver with no shader pipeline, a preset
    for the other backend, one this cannot safely extend -- and then the bar
    simply sits over the bottom of the game. The margin pass is read from
    ``overlay_dir``, as ``stage_assets`` left it.
    """
    backend = _backend_for(video_driver)
    if backend is None:
        return user_preset, None
    margin = cfg_path(Path(overlay_dir) / MARGIN_SHADER[backend].name)

    if user_preset:
        source = Path(user_preset)
        if source.suffix.lower() != f".{backend}p":
            return user_preset, None
        parsed = _absolute_passes(source)
        if parsed is None:
            return user_preset, None
        body, passes = parsed
        hidden = [f'shaders = "{passes}"', *body]
        # Appending a pass makes the console shader's last pass an
        # intermediate one, and an intermediate pass with no scale of its own
        # renders at the *console's* resolution -- 240x160 for a GBA -- where
        # a dot or CRT mask has no pixels to live in. So that pass is told to
        # render at the viewport's size already shrunk by the margin, and the
        # margin pass only places it, pixel for pixel: nothing is resampled.
        last = passes - 1
        last_keys = {f"{key}{last}" for key in (
            "scale_type", "scale_type_x", "scale_type_y", "scale", "scale_x", "scale_y")}
        kept = [line for line in body
                if not (_KEY_VALUE.match(line) and _KEY_VALUE.match(line).group(1) in last_keys)]
        shown = [f'shaders = "{passes + 1}"', *kept,
                 f'scale_type{last} = "viewport"',
                 f'scale{last} = "{1.0 - MARGIN:.6f}"',
                 f'shader{passes} = "{margin}"',
                 f'filter_linear{passes} = "false"',
                 f'scale_type{passes} = "viewport"']
    else:
        plain = ['shaders = "1"', f'shader0 = "{margin}"',
                 'filter_linear0 = "false"', 'scale_type0 = "viewport"']
        # The same pass with no margin: the game at full size, which is what
        # RetroArch would draw with no shader at all.
        hidden = [*plain, 'parameters = "MARGIN"', 'MARGIN = "0.0"']
        shown = plain

    folder = Path(runtime_dir) / "in_game_bar"
    folder.mkdir(parents=True, exist_ok=True)
    for stale in folder.iterdir():
        # "Next shader" walks everything in here: nothing but the pair.
        if stale.is_file():
            stale.unlink()
    suffix = f".{backend}p"
    (folder / f"{HIDDEN_PRESET}{suffix}").write_text("\n".join(hidden) + "\n", encoding="utf-8")
    shown_path = folder / f"{SHOWN_PRESET}{suffix}"
    shown_path.write_text("\n".join(shown) + "\n", encoding="utf-8")
    return str(shown_path), str(folder)
