# Built from a self-contained tree (pure-Python app + a vendored RetroArch
# AppImage), so skip debuginfo and the binary-reprocessing steps that would try
# to strip/mangle the bundled AppImage, and declare Requires by hand.
#
# `Version:` is templated: packaging/rpm/build.sh resolves it from
# src/openemux/__init__.py (the single source of truth) into the copy of this
# spec it hands to rpmbuild, so the version lives in one file and the *.src.rpm
# carries a concrete one. That SRPM is self-contained -- `rpmbuild --rebuild`,
# `mock` and COPR build it with no OpenEmux checkout anywhere, which the build
# proves on every run.
%global debug_package %{nil}
%global __brp_strip %{nil}
%global __brp_strip_static_archive %{nil}
%global __brp_strip_comment_note %{nil}
%global __brp_mangle_shebangs %{nil}
%global __brp_check_rpaths %{nil}
%global __requires_exclude .*
%global __provides_exclude .*

Name:           openemux
Version:        %{version}
Release:        1%{?dist}
Summary:        Linux-native emulator frontend for RetroArch

License:        MIT
URL:            https://github.com/guilhermefeitosa66/OpenEmux
# ExclusiveArch, not BuildArch: the vendored RetroArch AppImage is an x86_64
# binary, so this package can only be *built* somewhere that produces x86_64 --
# which is what ExclusiveArch says. BuildArch claims the opposite, that the
# contents are architecture-independent enough to be labelled by hand, and
# rpmlint calls it out (buildarch-instead-of-exclusivearch-tag).
ExclusiveArch:  x86_64
AutoReqProv:    no

# Generated by packaging/rpm/build.sh from the working tree. Not the GitHub
# archive URL: what is packaged is the tree as built, and a URL here would
# promise a byte-identical download that does not exist.
Source0:        %{name}-%{version}.tar.gz

# convert(1) renders the menu icon sizes; desktop-file-validate checks the
# installed entry in %%check; python3 runs the ScreenScraper credential
# injection (a no-op with no credential in the environment).
BuildRequires:  ImageMagick
BuildRequires:  desktop-file-utils
BuildRequires:  python3
# appstreamcli, for validating the metainfo the software centre reads.
BuildRequires:  appstream

# Targets Fedora 40+ (libadwaita >= 1.5, required by the Adwaita UI).
Requires:       python3 >= 3.10
Requires:       python3-gobject
Requires:       python3-cairo
Requires:       gtk4 >= 4.6
Requires:       libadwaita >= 1.5
Requires:       python3-pyyaml
# The game window reparents RetroArch's X11 window into ours (issue #199).
Requires:       python3-xlib
Requires:       librsvg2
# Cover art synced from libretro is WebP, and gdk-pixbuf has no built-in
# decoder for it. On Fedora the loader reaches a machine only as a *weak*
# dependency of gdk-pixbuf2-modules, so `rpm -ivh`, offline installs and
# --setopt=install_weak_deps=False all did without it -- and then every synced
# cover decoded to nothing and the card rendered blank, with one
# "cover decode failed" line in the log to say why (issue #251). The AppImage
# has bundled the loader from the start; this is the same dependency,
# declared rather than inherited from somebody else's Recommends.
Requires:       webp-pixbuf-loader
Requires:       adwaita-icon-theme
Requires:       shared-mime-info
# Hard, not weak: the vendored RetroArch AppImage is the only emulator this
# package ships, and its runtime needs libfuse.so.2 to mount itself. As a
# Recommends it arrived with `dnf install ./x.rpm` and with nothing else --
# `rpm -ivh`, --setopt=install_weak_deps=False and offline installs all
# skipped it, and the app then installed cleanly and could not launch a
# single game (issue #248).
Requires:       fuse-libs

%description
OpenEmux is a GTK4/Adwaita frontend that manages a ROM library and launches
games through RetroArch, inspired by OpenEmu. It bundles a RetroArch AppImage
and downloads libretro cores on first launch.

%prep
%autosetup

%build
# Nothing to compile. OpenEmux is pure Python; the RetroArch AppImage it
# vendors is shipped prebuilt and is deliberately left untouched (see the
# __brp_* overrides above).

%install
rm -rf %{buildroot}
DESTDIR=%{buildroot} ROOT_DIR="$PWD" sh packaging/common/stage_tree.sh

# stage_tree.sh writes the Debian layout, /usr/share/doc/openemux/copyright.
# On RPM the licence belongs in %%{_licensedir}, which the `%%license` lines
# below fill in themselves; leaving the Debian copy behind orphaned
# /usr/share/doc/openemux (owned by no package, left behind by `dnf remove`,
# and an rpmlint error).
rm -rf %{buildroot}/usr/share/doc/openemux

%check
# The desktop entry the package actually installs, not the one in the source
# tree -- stage_tree.sh rewrites Exec/TryExec on the way in.
desktop-file-validate \
  %{buildroot}/usr/share/applications/io.github.guilhermefeitosa66.OpenEmux.desktop
grep -q '^Exec=/usr/bin/openemux$' \
  %{buildroot}/usr/share/applications/io.github.guilhermefeitosa66.OpenEmux.desktop
# The file the software centre reads. --no-net so the build stays offline; the
# screenshot URLs are checked by tests/test_appstream_metainfo.py instead.
appstreamcli validate --no-net \
  %{buildroot}/usr/share/metainfo/io.github.guilhermefeitosa66.OpenEmux.metainfo.xml

%files
/opt/openemux
/usr/bin/openemux
/usr/share/applications/io.github.guilhermefeitosa66.OpenEmux.desktop
/usr/share/metainfo/io.github.guilhermefeitosa66.OpenEmux.metainfo.xml
/usr/share/icons/hicolor/*/apps/io.github.guilhermefeitosa66.OpenEmux.png
/usr/share/pixmaps/io.github.guilhermefeitosa66.OpenEmux.png
%license LICENSE
# Not a duplicate of LICENSE: about a third of what ships is third-party (the
# OpenEmu console icons, the Adwaita symbolic icons, the vendored RetroArch
# AppImage) and this is where their terms are recorded (issue #233).
%license packaging/common/copyright

# $1 is the number of copies of the package that will remain: 1 on a fresh
# install and 2 during an upgrade for %%post, 1 during an upgrade and 0 on the
# final erase for %%postun. Both caches are refreshed whenever the package
# lands, and rebuilt on erase only -- during an upgrade the incoming package's
# %%post already does it, and doing it again from the outgoing one's %%postun
# would rebuild the caches from a half-removed state.
%post
if command -v gtk-update-icon-cache >/dev/null 2>&1; then
  gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || :
fi
if command -v update-desktop-database >/dev/null 2>&1; then
  update-desktop-database -q /usr/share/applications || :
fi

%postun
if [ $1 -eq 0 ]; then
  if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache -q -t -f /usr/share/icons/hicolor || :
  fi
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database -q /usr/share/applications || :
  fi
fi

%changelog
* Wed Aug 19 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.11.3-1
- Never leave a game borderless and unmovable when the game window cannot adopt it
- Say what the game window is doing while it waits, and give up in seconds instead of twenty
- Keep RetroArch on X11 while embedding, so the window can actually be adopted
- Stop a gamepad's fullscreen button from breaking a working embed

* Sun Aug 16 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.11.2-1
- Stop writing per-launch settings into the user's own RetroArch configuration
- Give a game its decorated window back when the OpenEmux game window is off
- Find the host's audio server under Flatpak, so games no longer run at the monitor's refresh rate

* Sun Aug 16 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.11.1-1
- Closing the game window now really ends the emulator instead of leaving it playing with no window
- Closing the library window stops a running game with it

* Sat Aug 15 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.11.0-1
- Play inside an OpenEmux game window, with the emulator's controls in its header bar
- Ship a local database of 60,600 game names, so covers are found without guessing URLs
- Suggest the right game by name in the cover picker, including for misspelled queries
- Download covers in parallel and reveal them as they arrive instead of only at the end
- Keep save states, battery saves and artwork with a ROM when it is renamed
- Choose System, Light or Dark from Settings, or flip it from the header bar

* Sun Aug 02 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.10.2-1
- Grant the Flatpak read access to the RetroArch Flatpak cores dir, so games launch on Flatpak-only setups

* Fri Jul 31 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.10.1-1
- Fix games running several times too fast when RetroArch's audio driver fails to start

* Fri Jul 31 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.10.0-1
- Apply a saved remap to the running game, keeping its progress
- Configure a connected gamepad and the keyboard together, not either/or
- Add analog deadzone and sensitivity, rumble, latency and the remaining input knobs
- Choose which controller the core is told is plugged in, per console
- Add the missing system hotkeys, including disk control for multi-disc games
- Play the left analog stick from the keyboard, and let a pad's D-pad move it
- Bundle every symbolic icon the UI uses, so none go missing on any desktop
- Make missing artwork visible and recoverable; decode covers off the main thread
- Write keyboard bindings as key names RetroArch can resolve
- Set a console's default core and shader from the sidebar
- Complete the five stub locales and rename Preferences to Settings

* Mon Jul 27 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.9.2-1
- Give an imported image the whole area, with a trash button to clear it
- Put the artwork import controls and the save destination on a single row

* Mon Jul 27 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.9.1-1
- Fix a crash when acting on a ROM's context menu, and log the stack when one happens
- Sync a single ROM's cover or label straight from the menu, in the background
- Open the artwork manager from its own "Manage cover/label" entries
- Show search results on the library's grid, mark the pick, and allow cancelling a search
- Give an imported image the whole area, with one row of edit controls

* Mon Jul 27 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.9.0-1
- Pick a cartridge shell colour per game, from a palette of twelve
- Select several ROMs with Shift/Ctrl, the keyboard, or a gamepad selection mode
- Manage artwork per ROM: search every provider by name or hash, or import your own
- Order and toggle the artwork providers, with OpenEmux's own mirror as a new source
- Control the running game's volume and save states from the app or new hotkeys
- Fold the analog stick onto the D-pad, and map a turbo/autofire modifier
- Ship a Flatpak, installable as a bundle or from the OpenEmux repository

* Fri Jul 24 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.8.0-1
- Add a Welcome Assistant that tours OpenEmux's features on first launch
- Bundle ScreenScraper cover art support out of the box in official builds
- Fix console list items shifting when hovering over the sidebar
- Refresh the README and website screenshots for the current UI

* Thu Jul 23 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.7.0-1
- Choose the shader per ROM from the context menu, over the per-console setting
- Choose the libretro core per console (Preferences) and per ROM (context menu)
- Configure the library layout (view mode, sort, zoom) per console and per view
- Group games into custom collections in the sidebar, spanning consoles

* Thu Jul 23 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.6.0-1
- Add a View Mode selector: cover grid, cartridge grid and a compact list
- Add zoom controls for thumbnails (50%-200%), with Ctrl+plus/minus/0
- Sort the library by name, recently played, recently added, size or platform
- Track play history per ROM to support the recently-played order
- Follow the desktop language on first launch instead of defaulting to English
- Open the primary menu from the gamepad and restore focus after dialogs close
- Steer with the right analog stick as well as the left one
- Fix gamepad remapping capturing UI navigation instead of the binding

* Tue Jul 21 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.5.2-1
- Fix cartridge frames and cover art not rendering in the AppImage
- Degrade to the plain cover when a cartridge cannot be composited

* Tue Jul 21 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.5.1-1
- Fix the AppImage failing to start with "usr/bin/python3: not found"

* Tue Jul 21 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.5.0-1
- Navigate the whole library with a gamepad (RetroArch button convention)
- Full keyboard navigation plus shortcuts for play, rename, delete, favorite,
  rescan, import and cover sync
- Show what each control does in the bottom bar, per input device
- Lay the game grid out like an icon view, with fixed card sizes per console
- Fix the launcher picking a python3 without PyGObject (pyenv/conda/asdf)
- Stop a source run's desktop entry from shadowing the packaged one
- Drop Flatpak packaging

* Tue Jul 21 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.4.0-1
- Render every game inside its console cartridge, from vector artwork, on by default
- Turn the favorite star on a cover into a button
- Rename a ROM from the context menu, carrying artwork and playlists along
- Delete a ROM from the context menu, moving the file to the system trash
- Select several ROMs by dragging, then delete them or sync only their covers

* Mon Jul 20 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.3.1-1
- Keep the sidebar context menu open instead of closing it on button release
- Show icons next to context menu entries
- Add a three-dot button on ROM covers and sidebar consoles to open the menu
- Move the favorite star to the top-left corner of the cover

* Mon Jul 20 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.3.0-1
- Recognize ROMs inside .zip archives; extract for cores that need a real file
- Import ROMs from the UI, by button or drag and drop
- Map controls with the gamepad itself; up to four gamepad ports
- Optional ScreenScraper cover source, including cartridge labels
- Rotating tips status bar and a customizable fullscreen toggle
- Cancellable cover sync, console icons throughout, context menus

* Fri Jul 17 2026 Guilherme Feitoza <guilhermefeitosa66@gmail.com> - 1.2.0-1
- Per-console cover proportions and separate cartridge-label images
- Redesigned All library view with per-game console labels
- Startup check for new releases
- First native .deb and .rpm packages
